<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\ConsoleFramework\ConsoleFramework.csproj"/>
        <EmbeddedResource Include="GridTest.xaml">
            <LogicalName>ManyControls.GridTest.xaml</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
</Project>